config/routes.rb
Rails.application.routes.draw do
  resources :experiences do
    member do
      post :mark_as_helpful
      post :mark_as_not_helpful
    end
    collection do
      get 'search'
    end
  end
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  get "/profile" => "profile#index"
  root to: 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user, optional: true
  acts_as_taggable_on :tags

  validates_presence_of :title, :description, :insurance_provider
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_many :experiences
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  before_action :set_experience, only: %i[ show edit update destroy mark_as_helpful mark_as_not_helpful]
  before_action :authenticate_user!, only: %i[ new create edit update ]

  # GET /experiences or /experiences.json
  def index
    @experiences = Experience.all
  end

  def search
    @experiences = Experience.all.left_joins(:user).order("users.reputation_points DESC")
    @experiences = @experiences.tagged_with(params[:tags]) if params[:tags].present?
  end

  def mark_as_helpful
    @experience.user.reputation_points = @experience.user.reputation_points + 1
    @experience.user.save

    redirect_to @experience, notice: "Review submitted successfully, thank you!"
  end

  def mark_as_not_helpful
    @experience.user.reputation_points = @experience.user.reputation_points - 1
    @experience.user.save

    redirect_to @experience, notice: "Review submitted successfully, thank you!"
  end

  # GET /experiences/1 or /experiences/1.json
  def show
  end

  # GET /experiences/new
  def new
    @experience = Experience.new
  end

  # GET /experiences/1/edit
  def edit
  end

  # POST /experiences or /experiences.json
  def create
    @experience = Experience.new(experience_params)
    @experience.user = current_user

    respond_to do |format|
      if @experience.save
        format.html { redirect_to root_path, notice: "Experience was successfully created." }
        format.json { render :show, status: :created, location: @experience }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiences/1 or /experiences/1.json
  def update
    respond_to do |format|
      if @experience.update(experience_params)
        format.html { redirect_to experience_url(@experience), notice: "Experience was successfully updated." }
        format.json { render :show, status: :ok, location: @experience }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @experience.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiences/1 or /experiences/1.json
  def destroy
    @experience.destroy

    respond_to do |format|
      format.html { redirect_to experiences_url, notice: "Experience was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experience
      @experience = Experience.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def experience_params
      params.require(:experience).permit(:title, :description, :insurance_provider, :tag_list, :anonymous)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @experiences = Experience.order(created_at: :desc).limit(5)
    end
end

app/controllers/profile_controller.rb
class ProfileController < ApplicationController
    before_action :authenticate_user!
    def index
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/experiences_helper.rb
module ExperiencesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/profile_helper.rb
module ProfileHelper
end

app/views/experiences/_form.html.erb
<%= form_for @experience, :html => { :class => "form-horizontal experience" } do |f| %>

  <% if @experience.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@experience.errors.count, "error") %> prohibited this experience from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @experience.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control' %>
    </div>
    <%=f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :description, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_area :description, :class => 'form-control' %>
    </div>
    <%=f.error_span(:description) %>
  </div>
  <div class="form-group">
    <%= f.label :tag_lists, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :tag_list, :class => 'form-control', "data-role" => "tagsinput" %>
    </div>
  </div>
  <div class="form-group">
    <%= f.label :insurance_provider, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :insurance_provider, :class => 'form-control' %>
    </div>
    <%=f.error_span(:insurance_provider) %>
  </div>

  <div class="form-group">
    <%= f.label :anonymous, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.check_box :anonymous, :class => 'form-control' %>
    </div>
  </div>


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Share experience", :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                root_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/experiences/edit.html.erb
<%- model_class = Experience -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/experiences/index.html.erb
<%- model_class = Experience -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:user_id) %></th>
      <th><%= model_class.human_attribute_name(:verified) %></th>
      <th><%= model_class.human_attribute_name(:insurance_provider) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @experiences.each do |experience| %>
      <tr>
        <td><%= link_to experience.id, experience_path(experience) %></td>
        <td><%= experience.title %></td>
        <td><%= experience.description %></td>
        <td><%= experience.user_id %></td>
        <td><%= experience.verified %></td>
        <td><%= experience.insurance_provider %></td>
        <td><%=l experience.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_experience_path(experience), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      experience_path(experience),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_experience_path,
            :class => 'btn btn-primary' %>

app/views/experiences/new.html.erb
<%- model_class = Experience -%>
<div class="page-header">
  <h1>Share an insurance experience with us</h1>
</div>
<%= render :partial => 'form' %>

app/views/experiences/search.html.erb
<div>
  <form action="<%= search_experiences_path %>">
    <input class="form-control"  data-role="tagsinput" name="tags" placeholder="Type for tags"/>
    <input type="submit" value="search" class="btn btn-info" style="margin-top: 10px">
  </form>
</div>

<div class="list-group">
  <h2>Experiences matching your search: "<%= params[:tags] %>"</h2>
  <% @experiences.each do |experience| %>
    <a href="<%= experience_path(experience) %>" class="list-group-item list-group-item-action flex-column align-items-start">
      <div class="d-flex w-100 justify-content-between" style="margin-bottom: 10px">
        <h5 class="mb-1"><%= experience.title %> <%= "<span class='badge badge-success'>Verified</span>".html_safe if experience.verified %></h5>
        <small class="font-italic"><%= experience.anonymous ?  "anonymous - Reputation: #{experience.user.reputation_points}" : "#{experience.user.email} - Reputation: #{experience.user.reputation_points}" %></small>
      </div>
      <p class="mb-1"><%= experience.description.truncate(200) %></p>
      <p>
        <%= experience.tags.map { |tag|  "<span class='badge badge-pill badge-secondary' style='background-color:#28a745; margin-right: 2px;'>#{tag}</span>" }.join.html_safe %>
      </p>
    </a>
  <% end %>
</div>

app/views/experiences/show.html.erb
<div style="text-align:right; ">
  <%= link_to "Helpful", mark_as_helpful_experience_path(@experience), class: "btn btn-primary", method: :post %>
  <%= link_to "Not Helpful",  mark_as_not_helpful_experience_path(@experience), class: "btn btn-danger", method: :post %>
</div>

<div class="d-flex w-100 justify-content-between" style="margin-bottom: 10px">
  <h5 class="mb-1"><%= @experience.title %> <%= "<span class='badge badge-success'>Verified</span>".html_safe if @experience.verified %></h5>
  <small class="font-italic"><%= @experience.anonymous ?  "anonymous - Reputation: #{@experience.user.reputation_points}": "#{@experience.user.email} - Reputation: #{@experience.user.reputation_points}" %></small>
</div>
<p class="mb-1"><%= @experience.description %></p>
<p>Insurance Provider: <%= @experience.insurance_provider %></p>
<p>
  <%= @experience.tags.map { |tag|  "<span class='badge badge-pill badge-secondary' style='background-color:#28a745; margin-right: 2px;'>#{tag}</span>" }.join.html_safe %>
</p>

<div class="row bootstrap snippets bootdeys">
  <div class="col-md-12 col-sm-12">
    <div class="comment-wrapper">
      <div class="panel panel-info">
        <div class="panel-heading">
          Comment panel
        </div>
        <div class="panel-body">
          <textarea class="form-control" placeholder="write a comment..." rows="3"></textarea>
          <br>
          <button type="button" class="btn btn-info pull-right">Post</button>
          <div class="clearfix"></div>
          <hr>
          <ul class="media-list">
            <li class="media">
              <a href="#" class="pull-left">
                <img src="https://bootdey.com/img/Content/user_1.jpg" alt="" class="img-circle">
              </a>
              <div class="media-body">
                                <span class="text-muted pull-right">
                                    <small class="text-muted">30 min ago</small>
                                </span>
                <strong class="text-success">@MartinoMont</strong>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Lorem ipsum dolor sit amet, <a href="#">#consecteturadipiscing </a>.
                </p>
              </div>
            </li>
            <li class="media">
              <a href="#" class="pull-left">
                <img src="https://bootdey.com/img/Content/user_2.jpg" alt="" class="img-circle">
              </a>
              <div class="media-body">
                                <span class="text-muted pull-right">
                                    <small class="text-muted">30 min ago</small>
                                </span>
                <strong class="text-success">@LaurenceCorreil</strong>
                <p>
                  Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  Lorem ipsum dolor <a href="#">#ipsumdolor </a>adipiscing elit.
                </p>
              </div>
            </li>
            <li class="media">
              <a href="#" class="pull-left">
                <img src="https://bootdey.com/img/Content/user_3.jpg" alt="" class="img-circle">
              </a>
              <div class="media-body">
                                <span class="text-muted pull-right">
                                    <small class="text-muted">30 min ago</small>
                                </span>
                <strong class="text-success">@JohnNida</strong>
                <p>
                  Lorem ipsum dolor <a href="#">#sitamet</a> sit amet, consectetur adipiscing elit.
                </p>
              </div>
            </li>
          </ul>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/home/index.html.erb
<h1>Home Page</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Trust Insurance" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">TrustInsurance</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
            <li><%= link_to "about us", "#"  %></li>
            <li><%= link_to "Share", "/experiences/new"  %></li>
            <li><%= link_to "Verify your account", "/profile"  %></li>
          </ul>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-md-9 offset-md-3">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer class="navbar fixed-bottom">
        <p>&copy; Trust Insurance 2022</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>